### ISSUE TITLE
Allow documentation customization

### ISSUE THREAD

**Issue by miesch1** [RDunkley/XML-To-Data-Class#27]
Awesome utility man. This project has already saved me time and has great potential. I just have a few suggestions to make it even more usable. First, the default documentation is a definite bonus, but I would love the ability to override the default text with my my own text. This could be added to the GUI and saved off in the x2dconfig.

**Comment by RDunkley** [comment]
Elements, Attributes, Text and CDATA now have a text box on the GUI that allows you to customize the default text. It is also saved and loaded with the other settings. Thanks for submitting.
