### ISSUE TITLE
Allow Visibility Modification

### ISSUE THREAD

**Issue by miesch1** [RDunkley/XML-To-Data-Class#28]
Again, to make this utility more usable, it would be amazing if I could customize the visibility of the types and members that are generated. Most of the code I want to generate is fine being public, but adding an option to make it 'internal' would be great. Extra points would be awarded to make a type or member 'static' as well.

**Comment by RDunkley** [comment]
I like it. I added the ability to set elements to "public" or "internal" and attributes, CDATA, and text to "public", "protected", or "internal". It got a little weird with the properties and constructors of parent elements also having to be internal if a child is internal, but this makes sense based if the class itself is internal. Thanks for submitting.
